### PR TITLE
Replace the PERT Chart layour alorithm

### PR DESCRIPTION
**Pull request by oxinabox**
I am not happy with out the existing graph layout algorithms handle PERT charts.
Or Directed Acyclic Graphs more generally.

This is what the current (spring) layout comes up with:
spring

Here is a quick plot of the output of the new algorithm in this PR
dag

I haven't hooked it up properly to plotting but here is the new layout using this algorithm,
but here is a quick plot of the output.
It is basically the same as what I have drawn by hand for this chart (`c` and `d` are swapped though, I wonder if I can and a small term to favour having earlier nodes at the top).

The algorithm is the formulate the layout as a QP, which gets solved with JuMP / Ipopt.
Which is pretty fast.
The constraints are:
 - the column is set by the longest distance from the root node*.
 - The vertical placements must 1 unit apart
 - Minimize total squared vertical distance between lined nodes

(* method allows multiple root nodes because it works for all DAG but PERT charts just have 1)

### CODE REVIEW

**Comment by oxinabox** [comment]
Can probably relax the upper and lower bound constraints a bunch more, 
Just need to put some constraint on something so veritcal placement doesn't go off to a random point i think.
Maybe just constrain the first root to be at the origin.

**Comment by oxinabox** [comment]
This is basically a simplified version of Sugiyama layered graph drawing.
Especially the assignment to layers using longest path from root, and with how PERT charts are constrained to a single door and leaf.
https://en.m.wikipedia.org/wiki/Layered_graph_drawing

**Comment by rschwarz** [comment]
I've followed the discussion on Gitter and was curious how tools such as `dot` are implemented, so I tried to locate the relevant papers.

From what I've seen do far, it seems that the implementation is often done in multiple steps. These steps are presented as optimization problems, but then actually solved with heuristics. In particular, I found the steps:

1) reverse arcs to make graph acyclic (does not apply in your application?)

2) assign layers to nodes (you already have a heuristic based on longest paths?)

3) find order of nodes within each layer, in order to minimize edge crossings

4) find actual positions of nodes within layer (given order) to make edges short.

It seems to be that you're trying to do 3 and 4 in one go. If the order is given, I guess that 4) can actually be done well with a (convex) QP. But for 3) it might be better to deal with the discrete structure directly and formulate a MIP, or use some iterative improvement heuristic.

Further, with edges that span multiple layers, there's the trick of introducing artificial nodes on each layer to represent the edge going through. With this modification, the edge crossing only needs to consider adjacent layers.

**Comment by oxinabox** [comment]
yeah, pretty much my thoughts also.
I think combining 3 and 4 works decently, but I think is worth looking into seperating them.
I have decided to move this code into its own package: https://github.com/oxinabox/LayeredLayouts.jl

Then can implement multiple algorithms there.

**Comment by oxinabox** [comment]
Redid it using Compose.jl + LayeredLayouts.jl
image

Will merge once LayeredLayouts is registered

**Pull request merged**
